<%@ Page Language="C#" AutoEventWireup="true" CodeFile="razarpay.aspx.cs" Inherits="razarpay" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title></title>
</head>
<body>
    <form action="Success.aspx" method="post">
<script
        src="https://checkout.razorpay.com/v1/checkout.js"
        data-key="rzp_test_TvUjpIdUynbbsx" <%--/*Enter the Test API Key ID generated from Dashboard → Settings → API Keys--%>
        data-amount="500" <%--// Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.--%>
        data-currency="INR"<%--// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account--%>
        data-order_id="<%=orderId%>"<%--// Replace with the order_id generated by you in the backend.--%>
        data-buttontext="Pay with Razorpay"
        data-name=""
        data-description="test product"
        data-image="projectimages/pixx/download.jpg"
        data-prefill.name="Abhishek"
        data-prefill.email="abhisheksukumaran50@gmail.com"
        data-theme.color="#F37254"
    ></script>
<input type="hidden" name="hidden"/>
    </form>
</body>
</html>
